---
name: 'github-actions-template'
description: 'Template for creating new GitHub Actions'
inputs:
  target:
    description: Who you would like to say hello to
    required: false
    default: world
runs:
  using: composite
  steps:
    - name: configure AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_IAM_ROLE }}
        role-session-name: github-actions
        aws-region: ${{ vars.AWS_REGION }}