---
name: 'github-actions-template'
description: 'Template for creating new GitHub Actions'
inputs:
  target:
    description: Who you would like to say hello to
    required: false
    default: world
runs:
  using: composite
  steps:
    - shell: bash
      run: echo hello ${{ inputs.target }}
